# STUDENT NAME AND INFORMATION

Note: For the cell above, feel free to use the markdown code from the class Jupyter Notebook and modify it with your student information.

## DATA 601 - Spring 2024
### Homework Assignment 6

#### Due-date: Monday 4/29/2023 midnight.
The excercises in this homework provide instruction on what to do. Feel free to add as many code or markdown cells as you need. The main objective of this homework is to train a classification algorithm and predict a target. In this case we will be using the wine dataset from SKLearn and use various features of wine to predict a target. In this case the target will be defined as the "class". However, note that these algorithms can predict number as well as categorical values. The classification models steps (e.g., train, test, calculate metrics, etc)) discussed in class are the same here.

Wine Dataset:
- https://scikit-learn.org/stable/datasets/toy_dataset.html#wine-recognition-dataset
- https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_wine.html#sklearn.datasets.load_wine

SciKit Learn Datasets:
- https://scikit-learn.org/stable/datasets

Seaborn Datasets:
- https://seaborn.pydata.org/generated/seaborn.load_dataset.html
- https://github.com/mwaskom/seaborn-data

In [1]:
from sklearn.datasets import load_wine
import pandas as pd
import seaborn as sns

In [2]:
df, target = load_wine(return_X_y=True, as_frame=True) # Loads the data and target
df['wine_class'] = target.tolist() # Adds the target data as a new column in dataframe
df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,wine_class
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,2

# Question 1 (5 Points)
Create a new df_filtered dataframe and only include class 0 and 1 in our dataset. We will use this in our classification models below and only predict class 0 or 1.

# Question 2 (5 Points)
Split the data into training (80%) and testing (20%).

# Question 3 (10 Points)
Use SVM algorithm to predict the class and calculate metrics: Confustion Matrix, Accuracy, Sensitivity and Specificity.

# Question 4 (10 Points)
Use a random forest classifier to predict the class and calculate metrics: Confustion Matrix, Accuracy, Sensitivity and Specificity.

# Question 5 (10 Points)
How many datapoints do we have in this dataset? Provide thoughts and comments on the size of this dataset on at least two of the following:  
- Which of the classification models above performed better?
- What are some challenges of the size of this dataset?
- Would you feel comfortable with using this dataset for predictions?
- What could be some things that you could do for improving the outputs and performance of the models? This could include steps during the data collection, cleaning/preparation/transformation, testing, training steps and/or model deployment.

# Question 6 (5 Points)

We have the toy dataset loaded from SNS. The dataset is related to diamond characteristics. Please comment on the following questions. 
1. Comment on which features could we predict and which features could be potentially used for training?
2. What could be an appropriate model to use?

In [ ]:
diamonds = sns.load_dataset("diamonds")
diamonds.head()

# NOTEBOOK END